import * as opentype from "opentype.js";
import {
  FONT_METRICS,
  GLYPH_CHARS,
  type FontBuildInput,
  type FontBuildResult,
  type FontVerificationResult,
  type NormalizedPath,
  type NormalizedPathCommand,
  type GlyphModel,
  getUsableGlyphs,
  normalizeKerningPairs,
  normalizeSpacingSettings,
  resolveGlyphAdvance,
  sortGlyphsByAlphabet,
} from "./glyphModel";
import type { KerningPair } from "../shared/types";

export type BuildFontOptions = {
  styleName?: string;
  manufacturer?: string;
  description?: string;
};

export function buildFont(
  input: FontBuildInput,
  options: BuildFontOptions = {},
): FontBuildResult {
  const familyName = normalizeFamilyName(input.familyName);
  const usableGlyphs = getUsableGlyphs(input.glyphs);
  const spacing = normalizeSpacingSettings(input.spacing);
  const exportedKerningPairs = getExportedKerningPairs(spacing.kerningPairs, usableGlyphs);

  if (usableGlyphs.length === 0) {
    throw new Error("Generate at least one valid glyph before exporting.");
  }

  const warnings = collectBuildWarnings(input.glyphs, usableGlyphs);
  const glyphs = [
    createNotdefGlyph(),
    createSpaceGlyph(spacing.spaceWidth),
    ...sortGlyphsByAlphabet(usableGlyphs).map((glyph) =>
      createOpenTypeGlyph(glyph, spacing),
    ),
  ];

  const font = new opentype.Font({
    familyName,
    styleName: options.styleName ?? "Regular",
    unitsPerEm: FONT_METRICS.unitsPerEm,
    ascender: FONT_METRICS.ascender,
    descender: FONT_METRICS.descender,
    manufacturer: options.manufacturer ?? "Typegen",
    description:
      options.description ??
      "Generated by Typegen from Figma vector glyphs.",
    glyphs,
  });

  const arrayBuffer = addKerningTables(font.toArrayBuffer(), {
    kern: createKernTable(exportedKerningPairs, glyphs),
    GPOS: createGposTable(exportedKerningPairs, glyphs),
  });

  return {
    arrayBuffer,
    familyName,
    glyphCount: usableGlyphs.length,
    warnings,
    verification: verifyGeneratedFont(arrayBuffer, usableGlyphs, spacing, exportedKerningPairs),
  };
}

function createOpenTypeGlyph(glyph: GlyphModel, spacing: ReturnType<typeof normalizeSpacingSettings>) {
  return new opentype.Glyph({
    name: glyph.name || glyph.char,
    unicode: glyph.unicode,
    advanceWidth: positiveAdvanceWidth(resolveGlyphAdvance(glyph, spacing)),
    path: toOpenTypePath(glyph),
  });
}

function createNotdefGlyph() {
  return new opentype.Glyph({
    name: ".notdef",
    unicode: 0,
    advanceWidth: FONT_METRICS.notdefAdvanceWidth,
    path: new opentype.Path(),
  });
}

function createSpaceGlyph(spaceWidth: number) {
  return new opentype.Glyph({
    name: "space",
    unicode: 32,
    advanceWidth: positiveAdvanceWidth(spaceWidth),
    path: new opentype.Path(),
  });
}

function toOpenTypePath(glyph: GlyphModel) {
  const path = new opentype.Path();

  for (const normalizedPath of normalizeContourWinding(glyph.paths)) {
    for (const command of normalizedPath.commands) {
      switch (command.type) {
        case "M":
          path.moveTo(command.x, command.y);
          break;
        case "L":
          path.lineTo(command.x, command.y);
          break;
        case "C":
          path.curveTo(
            command.x1,
            command.y1,
            command.x2,
            command.y2,
            command.x,
            command.y,
          );
          break;
        case "Q":
          path.quadTo(command.x1, command.y1, command.x, command.y);
          break;
        case "Z":
          path.close();
          break;
      }
    }
  }

  return path;
}

type Point = { x: number; y: number };

type Segment =
  | { type: "L"; start: Point; end: Point }
  | { type: "C"; start: Point; c1: Point; c2: Point; end: Point }
  | { type: "Q"; start: Point; c1: Point; end: Point };

type Contour = {
  segments: Segment[];
  closed: boolean;
};

function normalizeContourWinding(paths: NormalizedPath[]): NormalizedPath[] {
  const contours = paths.flatMap(pathToContours);

  return contours.map((contour) => {
    const depth = countContainingContours(contour, contours);
    const shouldBePositive = depth % 2 === 0;
    const area = contourArea(contour);
    const normalized = area === 0 || (area > 0) === shouldBePositive ? contour : reverseContour(contour);

    return contourToPath(normalized);
  });
}

function pathToContours(path: NormalizedPath): Contour[] {
  const contours: Contour[] = [];
  let segments: Segment[] = [];
  let current: Point | null = null;
  let start: Point | null = null;
  let closed = false;

  const flush = () => {
    if (segments.length > 0) {
      contours.push({ segments, closed });
    }
    segments = [];
    current = null;
    start = null;
    closed = false;
  };

  for (const command of path.commands) {
    if (command.type === "M") {
      flush();
      current = { x: command.x, y: command.y };
      start = current;
      continue;
    }

    if (!current) {
      continue;
    }

    if (command.type === "L") {
      const end = { x: command.x, y: command.y };
      segments.push({ type: "L", start: current, end });
      current = end;
    } else if (command.type === "C") {
      const end = { x: command.x, y: command.y };
      segments.push({
        type: "C",
        start: current,
        c1: { x: command.x1, y: command.y1 },
        c2: { x: command.x2, y: command.y2 },
        end,
      });
      current = end;
    } else if (command.type === "Q") {
      const end = { x: command.x, y: command.y };
      segments.push({
        type: "Q",
        start: current,
        c1: { x: command.x1, y: command.y1 },
        end,
      });
      current = end;
    } else if (command.type === "Z") {
      if (start && !samePoint(current, start)) {
        segments.push({ type: "L", start: current, end: start });
        current = start;
      }
      closed = true;
      flush();
    }
  }

  flush();
  return contours;
}

function contourToPath(contour: Contour): NormalizedPath {
  if (contour.segments.length === 0) {
    return { commands: [] };
  }

  const commands: NormalizedPathCommand[] = [
    { type: "M", ...contour.segments[0].start },
  ];

  for (const segment of contour.segments) {
    if (segment.type === "L") {
      commands.push({ type: "L", ...segment.end });
    } else if (segment.type === "C") {
      commands.push({
        type: "C",
        x1: segment.c1.x,
        y1: segment.c1.y,
        x2: segment.c2.x,
        y2: segment.c2.y,
        ...segment.end,
      });
    } else {
      commands.push({
        type: "Q",
        x1: segment.c1.x,
        y1: segment.c1.y,
        ...segment.end,
      });
    }
  }

  if (contour.closed) {
    commands.push({ type: "Z" });
  }

  return { commands };
}

function reverseContour(contour: Contour): Contour {
  return {
    closed: contour.closed,
    segments: contour.segments
      .map((segment): Segment => {
        if (segment.type === "L") {
          return { type: "L", start: segment.end, end: segment.start };
        }

        if (segment.type === "C") {
          return {
            type: "C",
            start: segment.end,
            c1: segment.c2,
            c2: segment.c1,
            end: segment.start,
          };
        }

        return {
          type: "Q",
          start: segment.end,
          c1: segment.c1,
          end: segment.start,
        };
      })
      .reverse(),
  };
}

function contourArea(contour: Contour): number {
  const points = contourSamplePoints(contour);
  let area = 0;

  for (let index = 0; index < points.length; index++) {
    const current = points[index];
    const next = points[(index + 1) % points.length];
    area += current.x * next.y - next.x * current.y;
  }

  return area / 2;
}

function countContainingContours(contour: Contour, contours: Contour[]): number {
  return contours.filter((other) => other !== contour && contourInsideContour(contour, other)).length;
}

function contourInsideContour(inner: Contour, outer: Contour): boolean {
  const innerPoints = contourSamplePoints(inner);
  if (innerPoints.length === 0 || !boundsInsideBounds(contourBounds(innerPoints), contourBounds(contourSamplePoints(outer)))) {
    return false;
  }

  return innerPoints.every((point) => pointInContour(point, outer));
}

function pointInContour(point: Point, contour: Contour): boolean {
  const points = contourSamplePoints(contour);
  let inside = false;

  for (let currentIndex = 0, previousIndex = points.length - 1; currentIndex < points.length; previousIndex = currentIndex++) {
    const current = points[currentIndex];
    const previous = points[previousIndex];
    const crossesY = current.y > point.y !== previous.y > point.y;
    const xAtY = ((previous.x - current.x) * (point.y - current.y)) / (previous.y - current.y || 1) + current.x;
    if (crossesY && point.x < xAtY) {
      inside = !inside;
    }
  }

  return inside;
}

function contourBounds(points: Point[]): { xMin: number; yMin: number; xMax: number; yMax: number } {
  return {
    xMin: Math.min(...points.map((point) => point.x)),
    yMin: Math.min(...points.map((point) => point.y)),
    xMax: Math.max(...points.map((point) => point.x)),
    yMax: Math.max(...points.map((point) => point.y)),
  };
}

function boundsInsideBounds(
  inner: { xMin: number; yMin: number; xMax: number; yMax: number },
  outer: { xMin: number; yMin: number; xMax: number; yMax: number },
): boolean {
  return inner.xMin >= outer.xMin && inner.yMin >= outer.yMin && inner.xMax <= outer.xMax && inner.yMax <= outer.yMax;
}

function contourSamplePoints(contour: Contour): Point[] {
  const points: Point[] = [];
  for (const segment of contour.segments) {
    if (points.length === 0) {
      points.push(segment.start);
    }

    const steps = segment.type === "L" ? 1 : 8;
    for (let step = 1; step <= steps; step++) {
      points.push(pointOnSegment(segment, step / steps));
    }
  }

  return points;
}

function pointOnSegment(segment: Segment, t: number): Point {
  if (segment.type === "L") {
    return lerpPoint(segment.start, segment.end, t);
  }

  if (segment.type === "Q") {
    const a = lerpPoint(segment.start, segment.c1, t);
    const b = lerpPoint(segment.c1, segment.end, t);
    return lerpPoint(a, b, t);
  }

  const a = lerpPoint(segment.start, segment.c1, t);
  const b = lerpPoint(segment.c1, segment.c2, t);
  const c = lerpPoint(segment.c2, segment.end, t);
  const d = lerpPoint(a, b, t);
  const e = lerpPoint(b, c, t);
  return lerpPoint(d, e, t);
}

function lerpPoint(a: Point, b: Point, t: number): Point {
  return {
    x: a.x + (b.x - a.x) * t,
    y: a.y + (b.y - a.y) * t,
  };
}

function samePoint(a: Point, b: Point): boolean {
  return a.x === b.x && a.y === b.y;
}

function normalizeFamilyName(value: string): string {
  const trimmed = value.trim().replace(/\s+/g, " ");
  return trimmed.length > 0 ? trimmed : "Typegen Font";
}

function positiveAdvanceWidth(value: number): number {
  return Number.isFinite(value) && value > 0
    ? value
    : FONT_METRICS.defaultAdvanceWidth;
}

function collectBuildWarnings(
  inputGlyphs: GlyphModel[],
  usableGlyphs: GlyphModel[],
): string[] {
  const warnings = new Set<string>();

  if (usableGlyphs.length < GLYPH_CHARS.length) {
    warnings.add(`Font generated with ${usableGlyphs.length}/${GLYPH_CHARS.length} supported glyphs.`);
  }

  for (const glyph of inputGlyphs) {
    for (const warning of glyph.warnings) {
      warnings.add(`${glyph.char}: ${warning}`);
    }
  }

  return [...warnings];
}

function getExportedKerningPairs(pairs: KerningPair[], glyphs: GlyphModel[]): KerningPair[] {
  const exported = new Set(glyphs.map((glyph) => glyph.char));
  return normalizeKerningPairs(pairs).filter((pair) => exported.has(pair.left) && exported.has(pair.right));
}

function createKernTable(pairs: KerningPair[], glyphs: opentype.Glyph[]): Uint8Array | null {
  if (pairs.length === 0) {
    return null;
  }

  const glyphIndexByChar = new Map<string, number>();
  glyphs.forEach((glyph, index) => {
    if (glyph.unicode) {
      glyphIndexByChar.set(String.fromCharCode(glyph.unicode), index);
    }
  });

  const records = pairs
    .map((pair) => {
      const left = glyphIndexByChar.get(pair.left);
      const right = glyphIndexByChar.get(pair.right);
      return left === undefined || right === undefined ? null : { left, right, value: pair.value };
    })
    .filter((record): record is { left: number; right: number; value: number } => Boolean(record))
    .sort((a, b) => a.left - b.left || a.right - b.right);

  if (records.length === 0) {
    return null;
  }

  const nPairs = records.length;
  const subtableLength = 14 + nPairs * 6;
  const bytes = new Uint8Array(4 + subtableLength);
  const view = new DataView(bytes.buffer);
  let offset = 0;

  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, subtableLength); offset += 2;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, nPairs); offset += 2;

  const entrySelector = Math.floor(Math.log2(nPairs));
  const searchRange = Math.pow(2, entrySelector) * 6;
  const rangeShift = nPairs * 6 - searchRange;
  writeUint16(view, offset, searchRange); offset += 2;
  writeUint16(view, offset, entrySelector); offset += 2;
  writeUint16(view, offset, rangeShift); offset += 2;

  for (const record of records) {
    writeUint16(view, offset, record.left); offset += 2;
    writeUint16(view, offset, record.right); offset += 2;
    writeInt16(view, offset, record.value); offset += 2;
  }

  return bytes;
}

function createGposTable(pairs: KerningPair[], glyphs: opentype.Glyph[]): Uint8Array | null {
  if (pairs.length === 0) {
    return null;
  }

  const glyphIndexByChar = createGlyphIndexByChar(glyphs);
  const grouped = new Map<number, { right: number; value: number }[]>();

  for (const pair of pairs) {
    const left = glyphIndexByChar.get(pair.left);
    const right = glyphIndexByChar.get(pair.right);
    if (left === undefined || right === undefined) {
      continue;
    }

    const records = grouped.get(left) ?? [];
    records.push({ right, value: pair.value });
    grouped.set(left, records);
  }

  const leftGlyphs = [...grouped.keys()].sort((a, b) => a - b);
  if (leftGlyphs.length === 0) {
    return null;
  }

  for (const records of grouped.values()) {
    records.sort((a, b) => a.right - b.right);
  }

  const coverageLength = 4 + leftGlyphs.length * 2;
  const pairSetLengths = leftGlyphs.map((left) => 2 + (grouped.get(left)?.length ?? 0) * 4);
  const pairPosHeaderLength = 10 + leftGlyphs.length * 2;
  const pairPosLength = pairPosHeaderLength + coverageLength + pairSetLengths.reduce((total, length) => total + length, 0);
  const scriptListLength = 20;
  const featureListLength = 14;
  const lookupListLength = 12 + pairPosLength;
  const totalLength = 10 + scriptListLength + featureListLength + lookupListLength;
  const bytes = new Uint8Array(totalLength);
  const view = new DataView(bytes.buffer);
  const scriptListOffset = 10;
  const featureListOffset = scriptListOffset + scriptListLength;
  const lookupListOffset = featureListOffset + featureListLength;
  const lookupTableOffset = lookupListOffset + 4;
  const pairPosOffset = lookupTableOffset + 8;
  let offset = 0;

  writeUint32(view, offset, 0x00010000); offset += 4;
  writeUint16(view, offset, scriptListOffset); offset += 2;
  writeUint16(view, offset, featureListOffset); offset += 2;
  writeUint16(view, offset, lookupListOffset); offset += 2;

  offset = scriptListOffset;
  writeUint16(view, offset, 1); offset += 2;
  writeTag(bytes, offset, "DFLT"); offset += 4;
  writeUint16(view, offset, 8); offset += 2;
  writeUint16(view, offset, 4); offset += 2;
  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, 0xffff); offset += 2;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, 0); offset += 2;

  offset = featureListOffset;
  writeUint16(view, offset, 1); offset += 2;
  writeTag(bytes, offset, "kern"); offset += 4;
  writeUint16(view, offset, 8); offset += 2;
  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, 0); offset += 2;

  offset = lookupListOffset;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, 4); offset += 2;

  offset = lookupTableOffset;
  writeUint16(view, offset, 2); offset += 2;
  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, 8); offset += 2;

  offset = pairPosOffset;
  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, pairPosHeaderLength); offset += 2;
  writeUint16(view, offset, 0x0004); offset += 2;
  writeUint16(view, offset, 0); offset += 2;
  writeUint16(view, offset, leftGlyphs.length); offset += 2;
  let nextPairSetOffset = pairPosHeaderLength + coverageLength;
  for (const length of pairSetLengths) {
    writeUint16(view, offset, nextPairSetOffset); offset += 2;
    nextPairSetOffset += length;
  }

  writeUint16(view, offset, 1); offset += 2;
  writeUint16(view, offset, leftGlyphs.length); offset += 2;
  for (const left of leftGlyphs) {
    writeUint16(view, offset, left); offset += 2;
  }

  for (const left of leftGlyphs) {
    const records = grouped.get(left) ?? [];
    writeUint16(view, offset, records.length); offset += 2;
    for (const record of records) {
      writeUint16(view, offset, record.right); offset += 2;
      writeInt16(view, offset, record.value); offset += 2;
    }
  }

  return bytes;
}

function createGlyphIndexByChar(glyphs: opentype.Glyph[]): Map<string, number> {
  const glyphIndexByChar = new Map<string, number>();
  glyphs.forEach((glyph, index) => {
    if (glyph.unicode) {
      glyphIndexByChar.set(String.fromCharCode(glyph.unicode), index);
    }
  });
  return glyphIndexByChar;
}

type SfntRecord = {
  tag: string;
  checksum: number;
  offset: number;
  length: number;
  data: Uint8Array;
};

function addKerningTables(buffer: ArrayBuffer, kerningTables: Partial<Record<"kern" | "GPOS", Uint8Array | null>>): ArrayBuffer {
  const nextTables = Object.entries(kerningTables).filter((entry): entry is ["kern" | "GPOS", Uint8Array] => Boolean(entry[1]));
  if (nextTables.length === 0) {
    return buffer;
  }

  const source = new Uint8Array(buffer);
  const view = new DataView(buffer);
  const version = source.slice(0, 4);
  const replacedTags = new Set(nextTables.map(([tag]) => tag));
  const records = readSfntRecords(source, view).filter((record) => !replacedTags.has(record.tag as "kern" | "GPOS"));
  for (const [tag, data] of nextTables) {
    records.push({
      tag,
      checksum: computeChecksum([...data]),
      offset: 0,
      length: data.length,
      data,
    });
  }
  records.sort((a, b) => a.tag.localeCompare(b.tag));

  const numTables = records.length;
  const highestPowerOf2 = Math.pow(2, Math.floor(Math.log2(numTables)));
  const searchRange = 16 * highestPowerOf2;
  const entrySelector = Math.floor(Math.log2(highestPowerOf2));
  const rangeShift = numTables * 16 - searchRange;
  let offset = 12 + numTables * 16;

  for (const record of records) {
    offset = align4(offset);
    record.offset = offset;
    record.checksum = computeChecksum([...record.data]);
    offset += record.length;
  }

  const output = new Uint8Array(align4(offset));
  output.set(version, 0);
  const outputView = new DataView(output.buffer);
  writeUint16(outputView, 4, numTables);
  writeUint16(outputView, 6, searchRange);
  writeUint16(outputView, 8, entrySelector);
  writeUint16(outputView, 10, rangeShift);

  let recordOffset = 12;
  for (const record of records) {
    writeTag(output, recordOffset, record.tag);
    writeUint32(outputView, recordOffset + 4, record.checksum);
    writeUint32(outputView, recordOffset + 8, record.offset);
    writeUint32(outputView, recordOffset + 12, record.length);
    output.set(record.data, record.offset);
    recordOffset += 16;
  }

  setHeadChecksumAdjustment(output, outputView);
  return output.buffer;
}

function readSfntRecords(source: Uint8Array, view: DataView): SfntRecord[] {
  const numTables = view.getUint16(4);
  const records: SfntRecord[] = [];

  for (let index = 0; index < numTables; index++) {
    const recordOffset = 12 + index * 16;
    const tag = String.fromCharCode(...source.slice(recordOffset, recordOffset + 4));
    const offset = view.getUint32(recordOffset + 8);
    const length = view.getUint32(recordOffset + 12);
    records.push({
      tag,
      checksum: view.getUint32(recordOffset + 4),
      offset,
      length,
      data: source.slice(offset, offset + length),
    });
  }

  return records;
}

function setHeadChecksumAdjustment(output: Uint8Array, view: DataView): void {
  const numTables = view.getUint16(4);
  for (let index = 0; index < numTables; index++) {
    const recordOffset = 12 + index * 16;
    const tag = String.fromCharCode(...output.slice(recordOffset, recordOffset + 4));
    if (tag !== "head") {
      continue;
    }

    const headOffset = view.getUint32(recordOffset + 8);
    writeUint32(view, headOffset + 8, 0);
    writeUint32(view, headOffset + 8, (0xb1b0afba - computeChecksum([...output])) >>> 0);
    return;
  }
}

function computeChecksum(bytes: number[]): number {
  const padded = [...bytes];
  while (padded.length % 4 !== 0) {
    padded.push(0);
  }

  let sum = 0;
  for (let index = 0; index < padded.length; index += 4) {
    sum = (sum + (((padded[index] << 24) >>> 0) + (padded[index + 1] << 16) + (padded[index + 2] << 8) + padded[index + 3])) >>> 0;
  }

  return sum >>> 0;
}

function align4(value: number): number {
  return value % 4 === 0 ? value : value + (4 - (value % 4));
}

function writeTag(output: Uint8Array, offset: number, tag: string): void {
  for (let index = 0; index < 4; index++) {
    output[offset + index] = tag.charCodeAt(index);
  }
}

function writeUint16(view: DataView, offset: number, value: number): void {
  view.setUint16(offset, value);
}

function writeInt16(view: DataView, offset: number, value: number): void {
  view.setInt16(offset, value);
}

function writeUint32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset, value >>> 0);
}

function verifyGeneratedFont(
  arrayBuffer: ArrayBuffer,
  glyphs: GlyphModel[],
  spacing: ReturnType<typeof normalizeSpacingSettings>,
  kerningPairs: KerningPair[],
): FontVerificationResult {
  const parsed = opentype.parse(arrayBuffer);
  const verifiedGlyphs: FontVerificationResult["verifiedGlyphs"] = [];
  const failedGlyphs: FontVerificationResult["failedGlyphs"] = [];
  const verifiedKerningPairs: FontVerificationResult["verifiedKerningPairs"] = [];
  const failedKerningPairs: FontVerificationResult["failedKerningPairs"] = [];

  for (const glyph of sortGlyphsByAlphabet(glyphs)) {
    const parsedGlyph = parsed.charToGlyph(glyph.char);
    const expectedAdvance = positiveAdvanceWidth(resolveGlyphAdvance(glyph, spacing));
    const commandCount = parsedGlyph.path.commands.length;

    if (
      parsedGlyph.unicode === glyph.unicode &&
      parsedGlyph.advanceWidth === expectedAdvance &&
      commandCount > 0
    ) {
      verifiedGlyphs.push({
        char: glyph.char,
        unicode: parsedGlyph.unicode,
        advanceWidth: parsedGlyph.advanceWidth,
        commandCount,
      });
    } else {
      failedGlyphs.push(glyph.char);
    }
  }

  for (const pair of kerningPairs) {
    const leftGlyph = parsed.charToGlyph(pair.left);
    const rightGlyph = parsed.charToGlyph(pair.right);
    const value = (parsed as opentype.Font).getKerningValue(leftGlyph, rightGlyph);
    if (value === pair.value) {
      verifiedKerningPairs.push(pair);
    } else {
      failedKerningPairs.push(pair);
    }
  }

  return {
    parsedGlyphCount: parsed.glyphs.length,
    verifiedGlyphs,
    failedGlyphs,
    verifiedKerningPairs,
    failedKerningPairs,
  };
}
