import * as opentype from "opentype.js";
import {
  FONT_METRICS,
  GLYPH_CHARS,
  type FontBuildInput,
  type FontBuildResult,
  type FontVerificationResult,
  type GlyphModel,
  getUsableGlyphs,
  normalizeSpacingSettings,
  resolveGlyphAdvance,
  sortGlyphsByAlphabet,
} from "./glyphModel";

export type BuildFontOptions = {
  styleName?: string;
  manufacturer?: string;
  description?: string;
};

export function buildFont(
  input: FontBuildInput,
  options: BuildFontOptions = {},
): FontBuildResult {
  const familyName = normalizeFamilyName(input.familyName);
  const usableGlyphs = getUsableGlyphs(input.glyphs);
  const spacing = normalizeSpacingSettings(input.spacing);

  if (usableGlyphs.length === 0) {
    throw new Error("Generate at least one valid glyph before exporting.");
  }

  const warnings = collectBuildWarnings(input.glyphs, usableGlyphs);
  const glyphs = [
    createNotdefGlyph(),
    createSpaceGlyph(spacing.spaceWidth),
    ...sortGlyphsByAlphabet(usableGlyphs).map((glyph) =>
      createOpenTypeGlyph(glyph, spacing),
    ),
  ];

  const font = new opentype.Font({
    familyName,
    styleName: options.styleName ?? "Regular",
    unitsPerEm: FONT_METRICS.unitsPerEm,
    ascender: FONT_METRICS.ascender,
    descender: FONT_METRICS.descender,
    manufacturer: options.manufacturer ?? "Typegen",
    description:
      options.description ??
      "Generated by Typegen MVP from Figma vector glyphs.",
    glyphs,
  });

  const arrayBuffer = font.toArrayBuffer();

  return {
    arrayBuffer,
    familyName,
    glyphCount: usableGlyphs.length,
    warnings,
    verification: verifyGeneratedFont(arrayBuffer, usableGlyphs, spacing),
  };
}

function createOpenTypeGlyph(glyph: GlyphModel, spacing: ReturnType<typeof normalizeSpacingSettings>) {
  return new opentype.Glyph({
    name: glyph.name || glyph.char,
    unicode: glyph.unicode,
    advanceWidth: positiveAdvanceWidth(resolveGlyphAdvance(glyph, spacing)),
    path: toOpenTypePath(glyph),
  });
}

function createNotdefGlyph() {
  const path = new opentype.Path();
  path.moveTo(80, 0);
  path.lineTo(620, 0);
  path.lineTo(620, 700);
  path.lineTo(80, 700);
  path.close();
  path.moveTo(160, 80);
  path.lineTo(540, 620);
  path.moveTo(540, 80);
  path.lineTo(160, 620);

  return new opentype.Glyph({
    name: ".notdef",
    unicode: 0,
    advanceWidth: FONT_METRICS.notdefAdvanceWidth,
    path,
  });
}

function createSpaceGlyph(spaceWidth: number) {
  return new opentype.Glyph({
    name: "space",
    unicode: 32,
    advanceWidth: positiveAdvanceWidth(spaceWidth),
    path: new opentype.Path(),
  });
}

function toOpenTypePath(glyph: GlyphModel) {
  const path = new opentype.Path();

  for (const normalizedPath of glyph.paths) {
    for (const command of normalizedPath.commands) {
      switch (command.type) {
        case "M":
          path.moveTo(command.x, command.y);
          break;
        case "L":
          path.lineTo(command.x, command.y);
          break;
        case "C":
          path.curveTo(
            command.x1,
            command.y1,
            command.x2,
            command.y2,
            command.x,
            command.y,
          );
          break;
        case "Q":
          path.quadTo(command.x1, command.y1, command.x, command.y);
          break;
        case "Z":
          path.close();
          break;
      }
    }
  }

  return path;
}

function normalizeFamilyName(value: string): string {
  const trimmed = value.trim().replace(/\s+/g, " ");
  return trimmed.length > 0 ? trimmed : "Typegen Font";
}

function positiveAdvanceWidth(value: number): number {
  return Number.isFinite(value) && value > 0
    ? value
    : FONT_METRICS.defaultAdvanceWidth;
}

function collectBuildWarnings(
  inputGlyphs: GlyphModel[],
  usableGlyphs: GlyphModel[],
): string[] {
  const warnings = new Set<string>();

  if (usableGlyphs.length < GLYPH_CHARS.length) {
    warnings.add(`Font generated with ${usableGlyphs.length}/${GLYPH_CHARS.length} supported glyphs.`);
  }

  for (const glyph of inputGlyphs) {
    for (const warning of glyph.warnings) {
      warnings.add(`${glyph.char}: ${warning}`);
    }
  }

  return [...warnings];
}


function verifyGeneratedFont(
  arrayBuffer: ArrayBuffer,
  glyphs: GlyphModel[],
  spacing: ReturnType<typeof normalizeSpacingSettings>,
): FontVerificationResult {
  const parsed = opentype.parse(arrayBuffer);
  const verifiedGlyphs: FontVerificationResult["verifiedGlyphs"] = [];
  const failedGlyphs: FontVerificationResult["failedGlyphs"] = [];

  for (const glyph of sortGlyphsByAlphabet(glyphs)) {
    const parsedGlyph = parsed.charToGlyph(glyph.char);
    const expectedAdvance = positiveAdvanceWidth(resolveGlyphAdvance(glyph, spacing));
    const commandCount = parsedGlyph.path.commands.length;

    if (
      parsedGlyph.unicode === glyph.unicode &&
      parsedGlyph.advanceWidth === expectedAdvance &&
      commandCount > 0
    ) {
      verifiedGlyphs.push({
        char: glyph.char,
        unicode: parsedGlyph.unicode,
        advanceWidth: parsedGlyph.advanceWidth,
        commandCount,
      });
    } else {
      failedGlyphs.push(glyph.char);
    }
  }

  return {
    parsedGlyphCount: parsed.glyphs.length,
    verifiedGlyphs,
    failedGlyphs,
  };
}
