import type { FontBuildResult } from "./glyphModel";

export const FONT_MIME_TYPE = "font/otf";
export const FONT_EXTENSION = "otf";
export const SMOKE_TEST_EXTENSION = "html";

export function createFontBlob(arrayBuffer: ArrayBuffer): Blob {
  return new Blob([arrayBuffer], { type: FONT_MIME_TYPE });
}

export function createFontDownloadName(familyName: string): string {
  const baseName = createSafeBaseName(familyName);

  return `${baseName || "Typegen-Font"}.${FONT_EXTENSION}`;
}

export function createSmokeTestDownloadName(familyName: string): string {
  const baseName = createSafeBaseName(familyName);

  return `${baseName || "Typegen-Font"}-smoke-test.${SMOKE_TEST_EXTENSION}`;
}

export function downloadFont(result: FontBuildResult): void {
  const blob = createFontBlob(result.arrayBuffer);
  triggerDownload(blob, createFontDownloadName(result.familyName));
}

export function createSmokeTestHtml(
  result: FontBuildResult,
  sampleText = "ABC box @2+2",
): string {
  const fontData = arrayBufferToBase64(result.arrayBuffer);
  const familyName = escapeHtml(result.familyName);
  const cssFamilyName = escapeCssString(result.familyName);
  const displaySample = escapeHtml(sampleText);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${familyName} smoke test</title>
  <style>
    @font-face {
      font-family: "${cssFamilyName}";
      src: url("data:${FONT_MIME_TYPE};base64,${fontData}") format("opentype");
      font-weight: 400;
      font-style: normal;
    }

    body {
      margin: 0;
      padding: 32px;
      background: #f6f7f2;
      color: #202622;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    main {
      max-width: 900px;
    }

    h1 {
      margin: 0 0 8px;
      font-size: 20px;
    }

    p {
      margin: 0 0 20px;
      color: #5f6761;
    }

    .sample {
      border: 1px solid #d8ded2;
      border-radius: 8px;
      background: #fffef9;
      padding: 24px;
      font-family: "${cssFamilyName}", system-ui, sans-serif;
      font-size: 72px;
      line-height: 1.15;
      overflow-wrap: anywhere;
    }
  </style>
</head>
<body>
  <main>
    <h1>${familyName} smoke test</h1>
    <p>Generated by Typegen. If the font loaded correctly, supported glyphs below use your exported outlines.</p>
    <div class="sample">${displaySample}</div>
  </main>
</body>
</html>`;
}

export function downloadSmokeTestHtml(
  result: FontBuildResult,
  sampleText?: string,
): void {
  const blob = new Blob([createSmokeTestHtml(result, sampleText)], {
    type: "text/html;charset=utf-8",
  });

  triggerDownload(blob, createSmokeTestDownloadName(result.familyName));
}

function triggerDownload(blob: Blob, filename: string): void {
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = objectUrl;
  anchor.download = filename;
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  window.setTimeout(() => URL.revokeObjectURL(objectUrl), 0);
}

function createSafeBaseName(familyName: string): string {
  return familyName
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function arrayBufferToBase64(arrayBuffer: ArrayBuffer): string {
  const bytes = new Uint8Array(arrayBuffer);
  const chunkSize = 0x8000;
  let binary = "";

  for (let index = 0; index < bytes.length; index += chunkSize) {
    const chunk = bytes.subarray(index, index + chunkSize);
    binary += String.fromCharCode(...chunk);
  }

  return globalThis.btoa(binary);
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => {
    const entities: Record<string, string> = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;",
    };
    return entities[char];
  });
}

function escapeCssString(value: string): string {
  return value.replace(/["\\\n\r\f]/g, (char) => `\\${char}`);
}
